apiVersion: v1
kind: ServiceAccount
metadata:
  name: nightjar-ingest
  namespace: nightjar
  labels:
    app.kubernetes.io/name: nightjar-ingest
    app.kubernetes.io/version: "0.4.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/nightjar-ingest-dev
