apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nightjar-ingest.name" . }}
  labels:
    {{- include "nightjar-ingest.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_URL: {{ .Values.secrets.mongoUrl | quote }}
  REPUTATION_API_KEY: {{ .Values.secrets.reputationApiKey | quote }}
  WEBHOOK_SIGNING_SECRET: {{ .Values.secrets.webhookSigningSecret | quote }}
